Repository googleapis/nodejs-monitoring-dashboards, pull requests merged in 2020-07, with the labels that each got.

#95 build: use bazel build
  src/v1/dashboards_service_client.ts
  src/v1/dashboards_service_client_config.json
  synth.metadata
  synth.py
  test/gapic_dashboards_service_v1.ts
Labels: automerge, cla: yes

#96 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#98 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#100 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#103 chore: delete node 8 test templates
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none

#104 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#105 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#106 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#107 fix: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#109 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#110 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
