Repository googleapis/nodejs-monitoring-dashboards, pull requests merged in 2020-11, with the labels that each got.

#133 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#134 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/dashboards_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: monitoring, automerge, cla: yes

#137 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/dashboards_service_client.ts
  synth.metadata
Labels: api: monitoring, cla: yes, context: none

#139 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full
